<?php

function strings()
{
  $strings                                               = array();
  $strings["about_No_Database_connection"]               = "No hay conexión con la base de datos";
  $strings["about_Model_information"]                    = "Información del modelo";
  $strings["about_Model_name"]                           = "Nombre del modelo";
  $strings["about_Model_description"]                    = "Descripción del modelo";
  $strings["about_Model_theory"]                         = "Teoría del modelo";
  $strings["about_Modellers"]                            = "Modeladores";
  $strings["about_Modeller_lastname"]                    = "Apellido del modelador";
  $strings["about_Modeller_firstname"]                   = "Nombre del modelador";
  $strings["about_Modeller_email"]                       = "Correo del modelador";
  $strings["about_Files"]                                = "Archivos";
  $strings["about_Modelica_files"]                       = "Archivos Modelica";
  $strings["about_Graphic_files"]                        = "Archivos gráficos";
  $strings["about_Documentation"]                        = "Documentación";
  $strings["description_Select_an_experimentation_plant"]= "Seleccione una planta de experimentación";
  $strings["about_Download"]                             = "Descargar";
  $strings["about_Links_for_embedding"]                  = "Enlaces para incrustar";
  $strings["about_Model"]                                = "Modelo";
  $strings["about_Documentation"]                        = "Documentación";
  $strings["about_Pdf"]                                  = "Pdf";
  $strings["about_Practices"]                            = "Experimentos sugeridos";
  $strings["description_Documentation_file_not_found"]   = "No se ha encontrado el archivo de documentación";
  $strings["controls_Simulate"]                          = "Simular";
  $strings["controls_Reset"]                             = "Restaurar";
  $strings["tables_Download"]                            = "Descargar";
  
  $strings["adminblock_Update"]                          = "Actualizar";
  $strings["adminblock_Edit"]                            = "Editar";
  $strings["adminblock_Delete"]                          = "Eliminar";
  $strings["adminblock_Add"]                             = "Agregar";
  $strings["adminblock_No_name"]                         = "Sin nombre";
  $strings["adminblock_Delete_confirm"]                  = "¿Está seguro que desea eliminar el item?";
  $strings["adminblock_Yes"]                             = "SI";
  $strings["adminblock_No"]                              = "NO";
  $strings["adminblock_Actions"]                         = "Acciones";
  
  $strings["adminsection_Section"]                       = "Sección";
  $strings["adminsection_Identifier"]                    = "Identificador";
  $strings["adminsection_Section_name"]                  = "Nombre de la Sección";
  $strings["adminsection_Enabled"]                       = "Habilitado";
  $strings["adminsection_Description"]                   = "Descripción";
  $strings["adminsection_Daugther_sections"]             = "Secciones hijas";
  $strings["adminsection_Models"]                        = "Modelos";
  $strings["adminsection_Model_name"]                    = "Nombre del Modelo";
  $strings["adminsection_Father_section"]                = "Sección padre";

  $strings["adminmodel_Model"]                           = "Modelo";
  $strings["adminmodel_Identifier"]                      = "Identificador";
  $strings["adminmodel_Executable_name"]                 = "Nombre del archivo ejecutable";
  $strings["adminmodel_Model_name"]                      = "Nombre del modelo";
  $strings["adminmodel_Model_title"]                     = "Título del modelo";
  $strings["adminmodel_Enabled"]                         = "Habilitado";
  $strings["adminmodel_Description"]                     = "Descripción";
  $strings["adminmodel_Theory"]                          = "Teoría";
  $strings["adminmodel_Plots"]                           = "Figuras";
  $strings["adminmodel_2D_Animations"]                   = "Animaciones en 2D";
  $strings["adminmodel_Animation_name"]                  = "Nombre de la animación";
  $strings["adminmodel_Control_Groups"]                  = "Grupos de controles";
  $strings["adminmodel_Control_Group_name"]              = "Nombre del grupo de controles";
  $strings["adminmodel_Practices"]                       = "Experimentos sugeridos";
  $strings["adminmodel_Practices_name"]                  = "Nombre del experimento";
  $strings["adminmodel_Modellers"]                       = "Modeladores";
  $strings["adminmodel_Modeller_select"]                 = "Selección";
  $strings["adminmodel_Modeller_identifier"]             = "Identificador";
  $strings["adminmodel_Modeller_lastname"]               = "Apellidos";
  $strings["adminmodel_Modeller_firstname"]              = "Nombres";
  $strings["adminmodel_Modeller_email"]                  = "Correo";

  $strings["adminplot_Plot"]                             = "Figura";
  $strings["adminplot_Identifier"]                       = "Identificador";
  $strings["adminplot_Model_identifier"]                 = "Identificador del modelo";
  $strings["adminplot_Plot_name"]                        = "Nombre de la figura";
  $strings["adminplot_Enabled"]                          = "Habilitado";
  $strings["adminplot_Description"]                      = "Descripción";
  $strings["adminplot_Curves"]                           = "Curvas";
  $strings["adminplot_Horizontal_variable"]              = "Variable horizontal";
  $strings["adminplot_Minimum_horizontal_value"]         = "Valor mínimo de la variable horizontal";
  $strings["adminplot_Maximum_horizontal_value"]         = "Valor máximo de la variable horizontal";
  $strings["adminplot_Horizontal_divisions"]             = "Divisiones horizontales";
  $strings["adminplot_Horizontal_autoscale"]             = "Auto-escala horizontal";
  $strings["adminplot_Minimum_vertical_value"]           = "Valor mínimo de la variable vertical";
  $strings["adminplot_Maximum_vertical_value"]           = "Valor máximo de la variable vertical";
  $strings["adminplot_Vertical_divisions"]               = "Divisiones verticales";
  $strings["adminplot_Vertical_autoscale"]               = "Auto-escala vertical";
  $strings["adminplot_First_data"]                       = "Primer dato";
  $strings["adminplot_Curve_name"]                       = "Nombre de la curva";
  $strings["adminplot_Curve"]                            = "Curva";
  $strings["adminplot_Curve_name"]                       = "Nombre de la curva";
  $strings["adminplot_Legend"]                           = "Leyenda";
  $strings["adminplot_Vertical_variable"]                = "Variable vertical";
  $strings["adminplot_Color"]                            = "Color";

  $strings["adminmodelfiles_Executable"]                 = "Ejecutable (.tar.gz)";
  $strings["adminmodelfiles_Documentation"]              = "Documentación (.pdf)";
  $strings["adminmodelfiles_Modelica_files"]             = "Modelica (.tar.gz)";
  $strings["adminmodelfiles_Init_file"]                  = "Archivo init";
  $strings["adminmodelfiles_Results_file"]               = "Archivo de resultados";

  $strings["admincontrol_Identifier"]                    = "Identificador";
  $strings["admincontrol_Model_identifier"]              = "Valor";
  $strings["admincontrol_Name"]                          = "Nombre";
  $strings["admincontrol_Controls"]                      = "Controles";
  $strings["admincontrol_Control_name"]                  = "Nombre";
  $strings["admincontrol_Value"]                         = "Valor";
  $strings["admincontrol_Minimum"]                       = "Mínimo";
  $strings["admincontrol_Maximum"]                       = "Máximo";
  $strings["admincontrol_Step"]                          = "Incremento";
  $strings["admincontrol_Allowed_values"]                = "Valores permitidos";
  $strings["admincontrol_Description"]                   = "Descripción";
  $strings["admincontrol_Enabled"]                       = "Habilitado";
  $strings["admincontrol_Parameter"]                     = "Parámetro";

  $strings["admin2danim_2D_animation"]                   = "Animación en 2D";
  $strings["admin2danim_Identifier"]                     = "Identificador";
  $strings["admin2danim_Model_identifier"]               = "Identificador del modelo";
  $strings["admin2danim_Animation_name"]                 = "Nombre de la animación";
  $strings["admin2danim_Animation_title"]                = "Título";
  $strings["admin2danim_Animation_description"]          = "Descripción";
  $strings["admin2danim_Enabled"]                        = "Habilitado";
  $strings["admin2danim_SVG_file"]                       = "Archivo SVG";
  $strings["admin2danim_Duration"]                       = "Duración";
  $strings["admin2danim_Sample_time"]                    = "Tiempo de muestreo";
  $strings["admin2danim_Object_name"]                    = "Nombre";
  $strings["admin2danim_SVG_Type"]                       = "Tipo SVG";
  $strings["admin2danim_SVG_Identifier"]                 = "Identificador SVG";
  $strings["admin2danim_Modification"]                   = "Modificación";
  $strings["admin2danim_Animation"]                      = "Animación";
  $strings["admin2danim_Order"]                          = "Orden";
  $strings["admin2danim_Variable"]                       = "Variable";
  
  $strings["admin2deffect_2D_effect"]                    = "Efecto 2d";
  $strings["admin2deffect_Identifier"]                   = "Identificador";
  $strings["admin2deffect_Animation_identifier"]         = "Identificador de animación";
  $strings["admin2deffect_Name"]                         = "Nombre";
  $strings["admin2deffect_Description"]                  = "Descripción";
  $strings["admin2deffect_Type"]                         = "Tipo";
  $strings["admin2deffect_Enabled"]                      = "Habilitado";
  $strings["admin2deffect_SVG_animation_id"]             = "Identificador de animación SVG";
  $strings["admin2deffect_Control_variable"]             = "Variable de Control";
  $strings["admin2deffect_Auxiliar_variable"]            = "Variable Auxiliar";
  $strings["admin2deffect_Offset"]                       = "Offset";
  $strings["admin2deffect_Scale"]                        = "Escala";
  $strings["admin2deffect_RGB_minimum_color"]            = "Color RGB mínimo";
  $strings["admin2deffect_RGB_maximum_color"]            = "Color RGB máximo";
  $strings["admin2deffect_Minimum_color_value"]          = "Valor mínimo de Color";
  $strings["admin2deffect_Maximum_color_value"]          = "Valor máximo de Color";
  $strings["admin2deffect_Sequence"]                     = "Secuencia";
  
  $strings["adminpractice_Practice"]                     = "Experimento sugerido";
  $strings["adminpractice_Identifier"]                   = "Identificador";
  $strings["adminpractice_Practice_name"]                = "Nombre del experimento";
  $strings["adminpractice_Header"]                       = "Encabezado";
  $strings["adminpractice_Description"]                  = "Descripción";
  $strings["adminpractice_Enabled"]                      = "Habilitado";

  $strings["adminlogin_Wellcome_title"]                  = "UN-VirtualLab";
  $strings["adminlogin_Wellcome_subtitle"]               = "Laboratorio virtual de sistemas dinámicos";
  $strings["adminlogin_Wellcome_explanation"]            = "Ambiente Web de simulación de sistemas dinámicos basado en el lenguaje <a href='http://www.modelica.org' target='_new'>modelica</a><br><a href='http://www.unal.edu.co' target='_new'>Universidad Nacional de Colombia</a>";
  $strings["adminlogin_Lab"]                             = "Laboratorio";
  $strings["adminlogin_Configuration"]                   = "Configuración";
  $strings["adminlogin_User"]                            = "Usuario";
  $strings["adminlogin_Password"]                        = "Clave";
  
  $strings["adminlogout_Reports"]                        = "Reportes";
  $strings["adminlogout_Logout"]                         = "Cerrar sesión";

  $strings["adminreports_Update"]                        = "Actualizar";
  $strings["adminreports_Return"]                        = "Regresar";
  $strings["adminreports_Initial_month"]                 = "Mes inicial";
  $strings["adminreports_Initial_year"]                  = "Año inicial";
  $strings["adminreports_Final_month"]                   = "Mes final";
  $strings["adminreports_Final_year"]                    = "Año final";

  $strings["loggin_Simulation_Starts"]                   = "Inicio de simulación";
  $strings["loggin_Simulation_Ends"]                     = "Final de simulación ";

  return $strings;
}

?>

